services:
  vw-euda-mqtt:
    image: ghcr.io/stephanhenke/vw-euda-mqtt:latest
    container_name: vw-euda-mqtt
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./config.json:/config/config.json:ro
      - ./data:/config/data
    command: ["--config", "/config/config.json"]
