services:
  vwgroup-vehicle2mqtt:
    build: .
    container_name: vwgroup-vehicle2mqtt
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./config.json:/config/config.json:ro
      - ./data:/config/data
    command: ["--config", "/config/config.json"]
